name: AT
channels:
  - conda
dependencies:
  - python
  - jupyter
  - rise
  - numpy
  - matplotlib
  - seaborn
  - flask
  - requests
  - sqlalchemy
  - scikit-learn
  - pandas
  - requests
  - beautifulsoup4
